# Generated by Django 5.1.15 on 2026-06-27 09:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategoryStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('total_answered', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('accuracy_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='question_bank.questioncategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_category_stats',
                'indexes': [models.Index(fields=['user', 'category'], name='user_catego_user_id_780828_idx')],
                'unique_together': {('user', 'category')},
            },
        ),
    ]
