# Generated by Django 5.1.15 on 2026-07-11 09:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformOpsDaily",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("date", models.DateField(unique=True)),
                ("new_registrations", models.PositiveIntegerField(default=0)),
                ("exams_taken", models.PositiveIntegerField(default=0)),
                ("homework_submitted", models.PositiveIntegerField(default=0)),
                ("bookings_created", models.PositiveIntegerField(default=0)),
                ("tickets_created", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "platform_ops_daily",
                "ordering": ["-date"],
            },
        ),
    ]
