# Generated by Django 5.1.15 on 2026-07-15 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworksubmission",
            name="feedback",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="homeworksubmission",
            name="grade",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="homeworksubmission",
            name="grade_scale",
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="homeworksubmission",
            name="graded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homeworksubmission",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
