# Generated by Django 5.1.15 on 2026-08-05 16:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
        ("homework", "0002_homeworksubmission_feedback_homeworksubmission_grade_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworksubmission",
            name="attempt_number",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="homeworksubmission",
            name="is_late",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="homeworksubmission",
            name="response_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="homeworksubmission",
            name="returned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="homeworksubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("submitted", "Submitted"),
                    ("returned", "Returned for revision"),
                    ("graded", "Graded"),
                ],
                default="assigned",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="HomeworkAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="homework_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_links",
                        to="files.attachment",
                    ),
                ),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="homework.homework",
                    ),
                ),
            ],
            options={
                "db_table": "homework_attachments",
                "ordering": ["created_at"],
                "unique_together": {("homework", "attachment")},
            },
        ),
        migrations.CreateModel(
            name="HomeworkEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("returned", "Returned for revision"),
                            ("graded", "Graded"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("attempt_number", models.PositiveSmallIntegerField(default=1)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homework_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="homework.homeworksubmission",
                    ),
                ),
            ],
            options={
                "db_table": "homework_events",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["submission", "created_at"], name="homework_ev_submiss_a0b2cb_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HomeworkSubmissionFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("attempt_number", models.PositiveSmallIntegerField(default=1)),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_submission_links",
                        to="files.attachment",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="homework.homeworksubmission",
                    ),
                ),
            ],
            options={
                "db_table": "homework_submission_files",
                "ordering": ["created_at"],
                "unique_together": {("submission", "attachment")},
            },
        ),
    ]
