# Generated by Django 5.1.15 on 2026-07-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("exam_graded", "Exam Graded"),
                    ("exam_scheduled", "Exam Scheduled"),
                    ("homework_assigned", "Homework Assigned"),
                    ("homework_due", "Homework Due"),
                    ("announcement", "Announcement"),
                    ("system", "System"),
                ],
                default="system",
                max_length=30,
            ),
        ),
    ]
