# Generated by Django 5.1.15 on 2026-07-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_messagetemplate_announcement_announcementdelivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("exam_graded", "Exam Graded"),
                    ("exam_scheduled", "Exam Scheduled"),
                    ("homework_assigned", "Homework Assigned"),
                    ("homework_due", "Homework Due"),
                    ("announcement", "Announcement"),
                    ("system", "System"),
                    ("booking_requested", "Booking Requested"),
                    ("booking_confirmed", "Booking Confirmed"),
                    ("booking_cancelled", "Booking Cancelled"),
                    ("booking_completed", "Booking Completed"),
                    ("support_reply", "Support Reply"),
                    ("office_hours_reminder", "Office Hours Reminder"),
                    ("office_hours_canceled", "Office Hours Canceled"),
                    ("support_recommendation", "Support Recommendation"),
                    ("mentor_assigned", "Mentor Assigned"),
                    ("mentor_checkin_due", "Mentor Check-in Due"),
                    ("course_assigned", "Course Assigned"),
                ],
                default="system",
                max_length=30,
            ),
        ),
    ]
