# Generated by Django 5.1.15 on 2026-08-05 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VocabSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("title", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vocab_sections_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vocab_sections",
                "ordering": ["sort_order", "title", "id"],
            },
        ),
        migrations.CreateModel(
            name="VocabSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="vocabulary.vocabsection",
                    ),
                ),
            ],
            options={
                "db_table": "vocab_sets",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="VocabStudySession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("correct_count", models.PositiveIntegerField(default=0)),
                ("total_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocab_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vocab_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="vocabulary.vocabset",
                    ),
                ),
            ],
            options={
                "db_table": "vocab_study_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VocabWord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("word", models.CharField(db_index=True, max_length=120)),
                ("definition", models.TextField()),
                (
                    "part_of_speech",
                    models.CharField(
                        choices=[
                            ("noun", "Noun"),
                            ("verb", "Verb"),
                            ("adjective", "Adjective"),
                            ("adverb", "Adverb"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=24,
                    ),
                ),
                ("example", models.TextField(blank=True, default="")),
                ("synonyms", models.JSONField(blank=True, default=list)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "vocab_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="vocabulary.vocabset",
                    ),
                ),
            ],
            options={
                "db_table": "vocab_words",
                "ordering": ["sort_order", "word", "id"],
            },
        ),
        migrations.CreateModel(
            name="VocabWordProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("learning", "Learning"),
                            ("mastered", "Mastered"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=16,
                    ),
                ),
                ("correct_count", models.PositiveIntegerField(default=0)),
                ("wrong_count", models.PositiveIntegerField(default=0)),
                ("streak", models.PositiveIntegerField(default=0)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocab_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_rows",
                        to="vocabulary.vocabword",
                    ),
                ),
            ],
            options={
                "db_table": "vocab_word_progress",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="vocabset",
            index=models.Index(
                fields=["section", "sort_order"], name="vocab_sets_section_5df814_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vocabstudysession",
            index=models.Index(
                fields=["user", "vocab_set", "completed_at"], name="vocab_study_user_id_357e6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vocabstudysession",
            index=models.Index(
                fields=["user", "-created_at"], name="vocab_study_user_id_93291c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vocabword",
            index=models.Index(
                fields=["vocab_set", "sort_order"], name="vocab_words_vocab_s_6172ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vocabwordprogress",
            index=models.Index(fields=["user", "status"], name="vocab_word__user_id_a2ffca_idx"),
        ),
        migrations.AddConstraint(
            model_name="vocabwordprogress",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("user", "word"),
                name="uniq_vocab_progress_user_word",
            ),
        ),
    ]
