# Generated by Django 5.1.15 on 2026-07-06 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0005_studentprofile_status_changed_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "mentor_assignments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorCheckIn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("note", models.TextField()),
            ],
            options={
                "db_table": "mentor_checkins",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParentContactLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("message", "Message"),
                            ("meeting", "Meeting"),
                            ("other", "Other"),
                        ],
                        default="call",
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "parent_contact_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentee_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="mentor_assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="mentor_assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(fields=["mentor"], name="student_pro_mentor__f51b63_idx"),
        ),
        migrations.AddField(
            model_name="mentorassignment",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mentorassignment",
            name="ended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mentorassignment",
            name="mentor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mentor_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mentorassignment",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentor_assignments",
                to="academy.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="mentorcheckin",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mentorcheckin",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentor_checkins",
                to="academy.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="parentcontactlog",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="parentcontactlog",
            name="guardian",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contacts",
                to="academy.guardian",
            ),
        ),
        migrations.AddField(
            model_name="parentcontactlog",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_contacts",
                to="academy.studentprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="mentorassignment",
            index=models.Index(
                fields=["mentor", "ended_at"], name="mentor_assi_mentor__961bc3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mentorassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("ended_at__isnull", True)),
                fields=("profile",),
                name="uniq_active_mentor_per_student",
            ),
        ),
        migrations.AddIndex(
            model_name="mentorcheckin",
            index=models.Index(
                fields=["profile", "created_at"], name="mentor_chec_profile_72ec25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parentcontactlog",
            index=models.Index(
                fields=["profile", "created_at"], name="parent_cont_profile_a3e362_idx"
            ),
        ),
    ]
