# Generated by Django 5.1.15 on 2026-07-14 23:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0007_classsession_attendance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassScheduleRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("weekday", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("location", models.CharField(blank=True, default="", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "klass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_rules",
                        to="academy.class",
                    ),
                ),
            ],
            options={
                "db_table": "class_schedule_rules",
                "ordering": ["weekday", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["klass", "is_active"], name="class_sched_klass_i_2ca6fc_idx"
                    )
                ],
            },
        ),
    ]
