# Generated by Django 5.1.15 on 2026-08-05 16:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0009_studentnote"),
        ("files", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("post", "Post"),
                            ("announcement", "Announcement"),
                            ("material", "Material"),
                        ],
                        default="post",
                        max_length=20,
                    ),
                ),
                ("body", models.TextField()),
                ("is_pinned", models.BooleanField(default=False)),
                ("allow_comments", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="class_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "klass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="academy.class",
                    ),
                ),
            ],
            options={
                "db_table": "class_posts",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("body", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="class_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="academy.classpost",
                    ),
                ),
            ],
            options={
                "db_table": "class_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassPostAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_post_links",
                        to="files.attachment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="academy.classpost",
                    ),
                ),
            ],
            options={
                "db_table": "class_post_attachments",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="classpost",
            index=models.Index(
                fields=["klass", "-created_at"], name="class_posts_klass_i_0e35f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classcomment",
            index=models.Index(
                fields=["post", "created_at"], name="class_comme_post_id_c48a34_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classpostattachment",
            unique_together={("post", "attachment")},
        ),
    ]
