# Generated by Django 5.1.15 on 2026-07-11 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("actor_role", models.CharField(blank=True, max_length=20)),
                ("action", models.CharField(db_index=True, max_length=50)),
                ("target_type", models.CharField(blank=True, max_length=50)),
                ("target_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("target_label", models.CharField(blank=True, max_length=255)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "activity_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["actor", "-created_at"], name="activity_lo_actor_i_bd2550_idx"
                    ),
                    models.Index(
                        fields=["action", "-created_at"], name="activity_lo_action_61fa17_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_id"], name="activity_lo_target__77d758_idx"
                    ),
                ],
            },
        ),
    ]
