# Generated by Django 5.1.15 on 2026-08-06 01:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSuppression",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("email", models.EmailField(db_index=True, max_length=254, unique=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("bounced", "Hard bounce"),
                            ("complained", "Marked as spam"),
                            ("unsubscribed", "Unsubscribed"),
                            ("manual", "Blocked manually"),
                        ],
                        default="bounced",
                        max_length=24,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "email_suppressions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("to_email", models.EmailField(db_index=True, max_length=254)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("verify_email", "Email verification code"),
                            ("password_reset", "Password reset code"),
                            ("announcement", "Announcement"),
                            ("notification", "Notification"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=32,
                    ),
                ),
                ("subject", models.CharField(max_length=300)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("suppressed", "Suppressed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("error", models.TextField(blank=True, default="")),
                ("sent_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("reason", models.CharField(blank=True, default="", max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["to_email", "kind", "-created_at"],
                        name="email_messa_to_emai_b49d61_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"], name="email_messa_status_0c85f8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("verify_email", "Verify email"),
                            ("password_reset", "Reset password"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("code_hash", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "verification_codes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "purpose", "-created_at"],
                        name="verificatio_user_id_b669bf_idx",
                    )
                ],
            },
        ),
    ]
