# Generated by Django 5.1.15 on 2026-06-27 06:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        ('question_bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('max_attempts', models.SmallIntegerField(default=1)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_exams', to=settings.AUTH_USER_MODEL)),
                ('assigned_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='academy.class')),
                ('assigned_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_assignments',
            },
        ),
        migrations.CreateModel(
            name='ExamTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('practice', 'Practice Test'), ('past_paper', 'Past Paper'), ('mock', 'Mock Exam'), ('midterm', 'Midterm'), ('assessment', 'Assessment'), ('homework', 'Homework')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('module', models.CharField(choices=[('math', 'Math Only'), ('reading_writing', 'Reading & Writing Only'), ('full', 'Full Test')], default='full', max_length=20)),
                ('time_limit', models.SmallIntegerField(blank=True, null=True)),
                ('is_adaptive', models.BooleanField(default=False)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('academy', 'Academy Only')], db_index=True, default='academy', max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_templates',
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='in_progress', max_length=20)),
                ('current_section', models.SmallIntegerField(default=1)),
                ('current_question', models.SmallIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_remaining', models.IntegerField(blank=True, null=True)),
                ('client_session_data', models.JSONField(default=dict)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='assessments.examassignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='assessments.examtemplate')),
            ],
            options={
                'db_table': 'exam_sessions',
            },
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('module', models.CharField(choices=[('math', 'Math'), ('reading_writing', 'Reading & Writing')], max_length=20)),
                ('section_number', models.SmallIntegerField()),
                ('time_limit', models.SmallIntegerField(blank=True, null=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessments.examtemplate')),
            ],
            options={
                'db_table': 'exam_sections',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.SmallIntegerField(blank=True, null=True)),
                ('math_score', models.SmallIntegerField(blank=True, null=True)),
                ('rw_score', models.SmallIntegerField(blank=True, null=True)),
                ('total_correct', models.SmallIntegerField(default=0)),
                ('total_incorrect', models.SmallIntegerField(default=0)),
                ('total_skipped', models.SmallIntegerField(default=0)),
                ('total_questions', models.SmallIntegerField(default=0)),
                ('accuracy_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('time_spent_secs', models.IntegerField(default=0)),
                ('percentile', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('score_breakdown', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assessments.examsession')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='assessments.examtemplate')),
            ],
            options={
                'db_table': 'exam_results',
            },
        ),
        migrations.AddField(
            model_name='examassignment',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='assessments.examtemplate'),
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_appearances', to='question_bank.question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='assessments.examsection')),
            ],
            options={
                'db_table': 'exam_questions',
                'ordering': ['position'],
                'unique_together': {('section', 'position')},
            },
        ),
        migrations.CreateModel(
            name='ExamResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_answer', models.CharField(blank=True, max_length=10, null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('time_spent', models.SmallIntegerField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='question_bank.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.examsession')),
            ],
            options={
                'db_table': 'exam_responses',
                'unique_together': {('session', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['user', 'status'], name='exam_sessio_user_id_ba53c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examsection',
            unique_together={('exam', 'section_number')},
        ),
    ]
