# Generated by Django 5.1.15 on 2026-06-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='section_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
