# Generated by Django 5.1.15 on 2026-08-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_examtemplate_allow_pause"),
    ]

    operations = [
        migrations.AddField(
            model_name="examsession",
            name="feedback_mode",
            field=models.CharField(
                choices=[
                    ("none", "No feedback until submit"),
                    ("instant", "Mark each answer immediately"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="examtemplate",
            name="is_generated",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
