# Generated by Django 5.1.15 on 2026-08-06 00:49

from django.db import migrations, models

# The papers that are SAT, not practised. Same set that already refuses a pause:
# if the clock may not be stopped, the paper is invigilated, and an invigilated
# paper is sat in full screen.
INVIGILATED = ("mock", "midterm", "assessment", "past_paper")


def require_fullscreen_on_invigilated(apps, schema_editor):
    apps.get_model("assessments", "ExamTemplate").objects.filter(
        type__in=INVIGILATED
    ).update(requires_fullscreen=True)


def unrequire(apps, schema_editor):
    apps.get_model("assessments", "ExamTemplate").objects.update(requires_fullscreen=False)


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0004_examsession_feedback_mode_examtemplate_is_generated"),
    ]

    operations = [
        migrations.AddField(
            model_name="examsection",
            name="break_after_minutes",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="examtemplate",
            name="requires_fullscreen",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(require_fullscreen_on_invigilated, unrequire),
    ]
