# Generated by Django 5.1.15 on 2026-08-06 02:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0005_examsection_break_after_minutes_and_more"),
        ("question_bank", "0002_remove_question_parent_remove_question_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="examresponse",
            index=models.Index(
                fields=["question", "-answered_at"], name="exam_respon_questio_744129_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examsession",
            index=models.Index(
                fields=["user", "exam", "status"], name="exam_sessio_user_id_d00881_idx"
            ),
        ),
    ]
