# Generated by Django 5.1.15 on 2026-08-06 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0006_examresponse_exam_respon_questio_744129_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examquestion",
            name="routing",
            field=models.CharField(
                choices=[
                    ("standard", "Everyone"),
                    ("lower", "Lower form"),
                    ("upper", "Upper form"),
                ],
                db_index=True,
                default="standard",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="SessionModuleRouting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        choices=[
                            ("standard", "Everyone"),
                            ("lower", "Lower form"),
                            ("upper", "Upper form"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "decided_on_accuracy",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="assessments.examsection",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routings",
                        to="assessments.examsession",
                    ),
                ),
            ],
            options={
                "db_table": "exam_session_routings",
                "unique_together": {("session", "section")},
            },
        ),
    ]
