# Generated by Django 5.1.15 on 2026-07-15 05:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("enabled", models.BooleanField(default=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[("scheduled_daily", "Daily (scheduled)"), ("event", "On event")],
                        max_length=20,
                    ),
                ),
                ("event_key", models.CharField(blank=True, default="", max_length=64)),
                ("subject_type", models.CharField(default="student", max_length=20)),
                ("conditions", models.JSONField(default=dict)),
                ("actions", models.JSONField(default=list)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "automation_rules",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutomationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("subject_type", models.CharField(max_length=20)),
                ("subject_id", models.UUIDField()),
                ("subject_label", models.CharField(blank=True, default="", max_length=255)),
                ("run_date", models.DateField()),
                ("matched", models.BooleanField(default=False)),
                ("actions_taken", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("ok", "Acted"), ("skipped", "Skipped"), ("error", "Error")],
                        default="ok",
                        max_length=12,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="automation.automationrule",
                    ),
                ),
            ],
            options={
                "db_table": "automation_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["rule", "-created_at"], name="automation__rule_id_694863_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("rule", "subject_type", "subject_id", "run_date"),
                        name="uniq_rule_subject_day",
                    )
                ],
            },
        ),
    ]
