# Generated by Django 5.1.15 on 2026-07-15 04:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_tag_taggeditem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedFilter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("students", "Students"), ("leads", "Leads")],
                        default="students",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("params", models.JSONField(default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "crm_saved_filters",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["owner", "kind"], name="crm_saved_f_owner_i_149a32_idx")
                ],
            },
        ),
    ]
