# Generated by Django 5.1.15 on 2026-07-05 13:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "subject",
                    models.CharField(
                        choices=[("math", "Math"), ("reading_writing", "Reading & Writing")],
                        max_length=20,
                    ),
                ),
                ("topic", models.CharField(blank=True, default="", max_length=200)),
                ("reason", models.TextField(blank=True, default="")),
                ("scheduled_at", models.DateTimeField()),
                ("duration_minutes", models.PositiveSmallIntegerField(default=30)),
                (
                    "actual_duration_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No-show"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("join_url", models.URLField(blank=True, default="")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_teaching_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "support_bookings",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating",
                        to="support.supportbooking",
                    ),
                ),
            ],
            options={
                "db_table": "support_session_ratings",
            },
        ),
        migrations.CreateModel(
            name="SessionOutcome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("topics_covered", models.TextField(blank=True, default="")),
                ("homework", models.TextField(blank=True, default="")),
                ("next_recommendation", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcome",
                        to="support.supportbooking",
                    ),
                ),
            ],
            options={
                "db_table": "support_session_outcomes",
            },
        ),
        migrations.CreateModel(
            name="TeacherAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "subject",
                    models.CharField(
                        choices=[("math", "Math"), ("reading_writing", "Reading & Writing")],
                        max_length=20,
                    ),
                ),
                ("weekday", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("slot_minutes", models.PositiveSmallIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_availabilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "support_teacher_availability",
                "ordering": ["weekday", "start_time"],
            },
        ),
        migrations.AddIndex(
            model_name="supportbooking",
            index=models.Index(fields=["student", "status"], name="support_boo_student_437e37_idx"),
        ),
        migrations.AddIndex(
            model_name="supportbooking",
            index=models.Index(fields=["teacher", "status"], name="support_boo_teacher_f09bed_idx"),
        ),
        migrations.AddIndex(
            model_name="supportbooking",
            index=models.Index(
                fields=["teacher", "scheduled_at"], name="support_boo_teacher_4221a0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="supportbooking",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("status__in", ["pending", "confirmed"])
                ),
                fields=("teacher", "scheduled_at"),
                name="uniq_support_teacher_slot_live",
            ),
        ),
        migrations.AddIndex(
            model_name="teacheravailability",
            index=models.Index(
                fields=["subject", "is_active"], name="support_tea_subject_78c2a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacheravailability",
            index=models.Index(
                fields=["teacher", "is_active"], name="support_tea_teacher_2068e9_idx"
            ),
        ),
    ]
