# Generated by Django 5.1.15 on 2026-07-05 16:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_type"),
        ("support", "0002_supportticket_supportticketattachment_ticketreply_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("rule_key", models.CharField(max_length=50)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("acted", "Acted"),
                            ("dismissed", "Dismissed"),
                            ("expired", "Expired"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=12,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        choices=[("math", "Math"), ("reading_writing", "Reading & Writing")],
                        default="",
                        max_length=20,
                    ),
                ),
                ("topic", models.CharField(blank=True, default="", max_length=200)),
                ("evidence", models.JSONField(default=dict)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="support.supportbooking",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="notifications.notification",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "support_recommendations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="supportbooking",
            name="source_recommendation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="support.supportrecommendation",
            ),
        ),
        migrations.AddIndex(
            model_name="supportrecommendation",
            index=models.Index(fields=["student", "status"], name="support_rec_student_54dca4_idx"),
        ),
        migrations.AddIndex(
            model_name="supportrecommendation",
            index=models.Index(
                fields=["student", "rule_key", "status"], name="support_rec_student_2657f2_idx"
            ),
        ),
    ]
