# Generated by Django 5.1.15 on 2026-07-06 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0003_supportrecommendation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficeHour",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "subject",
                    models.CharField(
                        choices=[("math", "Math"), ("reading_writing", "Reading & Writing")],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("weekday", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("capacity", models.PositiveSmallIntegerField(default=25)),
                ("open_to_all", models.BooleanField(default=True)),
                ("location", models.CharField(blank=True, default="", max_length=200)),
                ("join_url", models.URLField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="office_hours",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "support_office_hours",
                "ordering": ["weekday", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="OfficeHourSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "subject",
                    models.CharField(
                        choices=[("math", "Math"), ("reading_writing", "Reading & Writing")],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("capacity", models.PositiveSmallIntegerField()),
                ("location", models.CharField(blank=True, default="", max_length=200)),
                ("join_url", models.URLField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("canceled", "Canceled"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=12,
                    ),
                ),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "office_hour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="support.officehour",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="office_hour_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "support_office_hour_sessions",
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="OfficeHourAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "rsvp",
                    models.CharField(
                        choices=[("joined", "Joined"), ("left", "Left")],
                        default="joined",
                        max_length=10,
                    ),
                ),
                ("attended", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="office_hour_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="support.officehoursession",
                    ),
                ),
            ],
            options={
                "db_table": "support_office_hour_attendances",
            },
        ),
        migrations.AddIndex(
            model_name="officehour",
            index=models.Index(
                fields=["subject", "is_active"], name="support_off_subject_75d483_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="officehoursession",
            index=models.Index(
                fields=["status", "starts_at"], name="support_off_status_9a212e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="officehoursession",
            index=models.Index(fields=["subject", "status"], name="support_off_subject_54507d_idx"),
        ),
        migrations.AddConstraint(
            model_name="officehoursession",
            constraint=models.UniqueConstraint(
                fields=("office_hour", "starts_at"), name="uniq_office_hour_occurrence"
            ),
        ),
        migrations.AddIndex(
            model_name="officehourattendance",
            index=models.Index(fields=["session", "rsvp"], name="support_off_session_a51002_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="officehourattendance",
            unique_together={("session", "student")},
        ),
    ]
