# Generated by Django 5.1.15 on 2026-07-06 08:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0004_officehour_officehoursession_officehourattendance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportOpsDaily",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("date", models.DateField(db_index=True, unique=True)),
                ("bookings_created", models.PositiveIntegerField(default=0)),
                ("bookings_completed", models.PositiveIntegerField(default=0)),
                ("bookings_cancelled", models.PositiveIntegerField(default=0)),
                ("bookings_no_show", models.PositiveIntegerField(default=0)),
                ("ratings_count", models.PositiveIntegerField(default=0)),
                (
                    "ratings_avg",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
                ),
                ("tickets_created", models.PositiveIntegerField(default=0)),
                ("tickets_answered", models.PositiveIntegerField(default=0)),
                (
                    "tickets_avg_response_minutes",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
                ),
                ("office_hours_sessions", models.PositiveIntegerField(default=0)),
                ("office_hours_attended", models.PositiveIntegerField(default=0)),
                ("recommendations_created", models.PositiveIntegerField(default=0)),
                ("recommendations_acted", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "support_ops_daily",
                "ordering": ["-date"],
                "indexes": [models.Index(fields=["date"], name="support_ops_date_6c4fbb_idx")],
            },
        ),
    ]
