# Generated by Django 5.1.15 on 2026-06-27 06:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('color', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'db_table': 'qb_tags',
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('module', models.CharField(choices=[('math', 'Math'), ('reading_writing', 'Reading & Writing')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='question_bank.questioncategory')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'qb_categories',
                'ordering': ['module', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.SmallIntegerField(default=1)),
                ('module', models.CharField(choices=[('math', 'Math'), ('reading_writing', 'Reading & Writing')], db_index=True, max_length=20)),
                ('difficulty', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('stem', models.TextField()),
                ('stem_image_url', models.URLField(blank=True, null=True)),
                ('has_math', models.BooleanField(default=False)),
                ('passage', models.TextField(blank=True, null=True)),
                ('passage_image_url', models.URLField(blank=True, null=True)),
                ('answer_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('grid_in', 'Grid-In')], default='mcq', max_length=10)),
                ('correct_answer', models.CharField(max_length=10)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('explanation_image_url', models.URLField(blank=True, null=True)),
                ('source', models.CharField(choices=[('official', 'Official SAT'), ('custom', 'Custom'), ('imported', 'Imported')], default='custom', max_length=20)),
                ('source_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='question_bank.question')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_questions', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='question_bank.questioncategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='questions', to='question_bank.questiontag')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='question_bank.question')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1)),
                ('text', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='question_bank.question')),
            ],
            options={
                'db_table': 'question_choices',
                'ordering': ['sort_order'],
                'unique_together': {('question', 'label')},
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['status', 'module'], name='questions_status_3a547e_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['status', 'category'], name='questions_status_d25e30_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['status', 'difficulty'], name='questions_status_bdd87e_idx'),
        ),
    ]
