# Generated by Django 5.1.15 on 2026-08-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='question',
            name='version',
        ),
    ]
