# Generated by Django 5.1.15 on 2026-07-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("public", "Public User"),
                    ("student", "Academy Student"),
                    ("teacher", "Teacher"),
                    ("receptionist", "Receptionist"),
                    ("academic_manager", "Academic Manager"),
                    ("admin", "Admin"),
                ],
                db_index=True,
                default="public",
                max_length=20,
            ),
        ),
    ]
