# Generated by Django 5.1.15 on 2026-07-11 08:35

import apps.identity.models
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_org_setting(apps, schema_editor):
    """Create the singleton row, defaulting the display timezone to the server's
    canonical TIME_ZONE. Idempotent."""
    OrgSetting = apps.get_model("identity", "OrgSetting")
    OrgSetting.objects.get_or_create(
        key="org",
        defaults={"display_timezone": getattr(settings, "TIME_ZONE", "Asia/Tashkent")},
    )


def unseed_org_setting(apps, schema_editor):
    OrgSetting = apps.get_model("identity", "OrgSetting")
    OrgSetting.objects.filter(key="org").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0002_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "key",
                    models.CharField(default="org", editable=False, max_length=16, unique=True),
                ),
                ("academy_name", models.CharField(blank=True, default="", max_length=200)),
                ("academic_year", models.CharField(blank=True, default="", max_length=20)),
                ("display_timezone", models.CharField(default="Asia/Tashkent", max_length=64)),
                (
                    "grading_thresholds",
                    models.JSONField(default=apps.identity.models.default_grading_thresholds),
                ),
                ("logo_url", models.URLField(blank=True, default="", max_length=500)),
                ("default_email_sender", models.EmailField(blank=True, default="", max_length=254)),
                ("feature_flags", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "org_settings",
            },
        ),
        migrations.RunPython(seed_org_setting, unseed_org_setting),
    ]
